SET DEFINE OFF;
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    PASSWORD, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (1, 1, 10001, 208, 'Md Mahram Ali', 
    '1', 801, 1001, 'mahram', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    PASSWORD, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (2, 1, 10002, 208, 'Shamim', 
    '1', 801, 1002, 'shamim', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    PASSWORD, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (3, 1, 10003, 208, 'Md Tanim', 
    '1', 801, 1003, 'tanim', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    PASSWORD, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (4, 1, 10004, 208, 'Mst Taslima', 
    '1', 735, 1004, 'taslima', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    PASSWORD, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (5, 1, 10005, 208, 'Mst Happy Akhter', 
    '1', 734, 1005, 'happy', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    PASSWORD, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (6, 1, 10006, 208, 'Mst Juma Akter', 
    '1', 734, 1006, 'juma', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMAIL, EMPLOYEE_ID, GROUP_ID, 
    LAST_NAME, PASSWORD, USER_BRANCH_ID, USER_ID, USER_NAME, 
    USER_STATUS, USER_TYPE)
 Values
   (7, 1, 'ashraf.uddin@al-arafahbank.com', 10007, 208, 
    'MD. ASHRAF UDDIN', '1', 805, 1007, 'asraf', 
    'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    PASSWORD, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (8, 1, 10008, 208, 'MD. JASHIM UDDIN', 
    '1', 805, 1008, 'jasmin', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (9, 1, 10009, 208, 'MD. HASAN AL  HAKIM', 
    805, 1009, 'hasan ', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (10, 1, 10010, 208, 'SALAHUDDIN', 
    360, 1010, 'salahuddin', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMAIL, EMPLOYEE_ID, GROUP_ID, 
    LAST_NAME, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (11, 1, 'md.zubayer@yahoo.com', 10011, 208, 
    'MD. WALID AL ZUBAYER', 360, 1011, 'zubayer', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (12, 1, 10012, 208, 'MD.  AHANAF SHARIAR ALVEE', 
    360, 1012, 'ahnaf', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (13, 1, 10013, 208, 'JAMAL HOSSAIN', 
    360, 1013, 'jamal2', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (14, 1, 10014, 208, 'MD. SOHAG SARDAR', 
    809, 1014, 'sohag', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (15, 1, 10015, 208, 'ABU NAYEEM MOHAMMAD  IFTEKHAR', 
    809, 1015, 'nayeem', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (16, 1, 10016, 208, 'MD. MILON HOSSAIN', 
    809, 1016, 'milon', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (17, 1, 10017, 208, 'NAEM UDDIN', 
    310, 1017, 'naem', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (18, 1, 10018, 208, 'Md. Musa Kazem', 
    310, 1018, 'musa', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (19, 1, 10019, 208, 'MD. AMIR HOSSAIN', 
    310, 1019, 'amir', 'DISABLED', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (20, 1, 10020, 208, 'MD. ENAMUL HAQUE', 
    310, 1020, 'enamul', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (21, 1, 10021, 208, 'MIZANUR RAHMAN', 
    105, 1021, 'mizanur', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (22, 1, 10022, 208, 'ABU BAKAR SIDDIQUE', 
    106, 1022, 'bakar', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (23, 1, 10023, 208, 'MUHAMMAD ABDUL MANNAN', 
    104, 1023, 'mannan', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (24, 1, 10024, 208, 'MOHAMMAD ALAMGIR  SIDDIQUI', 
    107, 1024, 'alamgi', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (25, 1, 10025, 208, 'MD. SAGIR HOSSEN', 
    105, 1025, 'sagir', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMAIL, EMPLOYEE_ID, GROUP_ID, 
    LAST_NAME, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (26, 1, 'pavel_510@yahoo.com', 10026, 208, 
    'AKIBUL KOWSER PAHLOWAN', 105, 1026, 'kowser', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (27, 1, 10027, 208, 'MD. SHAHARIAR JAMAL', 
    104, 1027, 'jamal', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMAIL, EMPLOYEE_ID, GROUP_ID, 
    LAST_NAME, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (28, 1, 'shafikul2439@al-arafahbank.com', 10028, 208, 
    'MD. SHAFIKUL ISLAM', 105, 1028, 'shafikul', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (29, 1, 10029, 208, 'MD. MOINUL HAQUE', 
    801, 1029, 'moinul', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMAIL, EMPLOYEE_ID, GROUP_ID, 
    LAST_NAME, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (30, 1, 'sharifah.billah@yahoo.com', 10030, 208, 
    'MOST. SHARIFA BILLAH', 104, 1030, 'sharifa', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMAIL, EMPLOYEE_ID, GROUP_ID, 
    LAST_NAME, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (31, 1, 'enam2012@al-arafahbank.com', 10031, 208, 
    'MD. ENAMUL HAQUE', 104, 1031, 'enamul', 'ACTIVE', 
    'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (32, 1, 10032, 208, 'MD. SOHEL', 
    103, 1032, 'sohel', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (33, 1, 10033, 208, 'MD.  ALAMGIR HOSSAIN', 
    103, 1033, 'alamgi2', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (34, 1, 10034, 208, 'MOKBUL AHMED', 
    130, 1034, 'mokbul', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (35, 1, 10035, 208, 'MOHAMMAD ROKAN UDDIN', 
    104, 1035, 'rokan', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (36, 1, 10036, 208, 'SYEDA MAHBUBA KHATUN', 
    105, 1036, 'mahbuba', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (37, 1, 10037, 208, 'MUHAMMAD MOSHIUR RAHMAN', 
    105, 1037, 'moshiur', 'ACTIVE', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMPLOYEE_ID, GROUP_ID, LAST_NAME, 
    USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, USER_TYPE)
 Values
   (38, 1, 10038, 208, 'S. M. WALI SEZAN', 
    105, 1038, 'sezan', 'DISABLED', 'APPLICATION_USER');
Insert into SECU_USER
   (ID, DEPARTMENT_ID, EMAIL, EMPLOYEE_ID, GROUP_ID, 
    LAST_NAME, USER_BRANCH_ID, USER_ID, USER_NAME, USER_STATUS, 
    USER_TYPE)
 Values
   (39, 1, 'amin2899@al-arafahbank.com', 10039, 208, 
    'MD. AMIN ULLAH', 103, 1039, 'amin', 'ACTIVE', 
    'APPLICATION_USER');
COMMIT;
